name: Acorn Preview
description: Deploy a preview build of a branch to a cluster
inputs:
  args:
    description: The arguments to pass to acorn run
    required: false
    default: ""
  image_args:
    description: The arguments to pass to the acorn image
    required: false
    default: ""
  registry:
    description: The registry to pull from
    required: false
    default: ghcr.io
  username:
    description: The username to use for authentication with the registry
    required: false
    default: ${{ github.actor }}
  password:
    description: The password to use for authentication with the registry
    required: false
    default: ""
  image:
    description: The name of the image to pull
    required: false
    default: ${{ github.repository }}
  name:
    description: The name prefix of the created app
    required: true
  kubeconfig:
    description: The kubeconfig to use for acorn
    required: true
  token:
    description: GitHub Token
    required: true
runs:
  using: "composite"
  steps:
    - name: Check for preview deployment trigger
      uses: khan/pull-request-comment-trigger@v1.1.0
      id: check
      with:
        trigger: '#preview'
        reaction: eyes
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - uses: actions/checkout@v3
      if: steps.check.outputs.triggered == 'true'

    - name: Build and push acorn image
      uses: infinytum/acorn-actions/build-and-push@main
      if: steps.check.outputs.triggered == 'true'
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        image: ${{ inputs.image }}
        tag: pr-${{ github.event.issue.number }}

    - name: Install newly built acorn image to cluster
      uses: infinytum/acorn-actions/install@main
      if: steps.check.outputs.triggered == 'true'
      id: install
      with:
        kubeconfig: ${{ inputs.kubeconfig }}
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        image: ${{ inputs.image }}
        tag: pr-${{ github.event.issue.number }}
        args: ${{ inputs.args }}
        image_args: ${{ inputs.image_args }}
        name: ${{ inputs.name }}-pr-${{ github.event.issue.number }}

    - name: Comment PR with acorn run output
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          **Preview Build was deployed**
          <details>
            <summary>Acorn Logs</summary>
            ${{ steps.install.outputs.acorn_log }}
          </details>
        comment_tag: Preview Build was deployed

    - name: Uninstall acorn image from cluster
      uses: infinytum/acorn-actions/uninstall@main
      if: github.event_name == 'pull_request'
      with:
        kubeconfig: ${{ inputs.kubeconfig }}
        args: "-a -f"
        name: ${{ inputs.name }}-pr-${{ github.event.number }}
        
    - name: Mark preview deployment as complete
      uses: khan/pull-request-comment-trigger@v1.1.0
      if: steps.check.outputs.triggered == 'true'
      id: feedback
      with:
        trigger: '#preview'
        reaction: rocket
      env:
        GITHUB_TOKEN: ${{ inputs.token }}