name: Acorn Build and Push
description: Build and push Acorn images
inputs:
  push:
    description: Push the built image to the registry
    required: false
    default: "true"
  registry:
    description: The registry to push to
    required: false
    default: ghcr.io
  username:
    description: The username to use for authentication with the registry
    required: false
    default: ${{ github.actor }}
  password:
    description: The password to use for authentication with the registry
    required: false
    default: ""
  image:
    description: The name of the image to build
    required: false
    default: ${{ github.repository }}
  tag:
    description: The tag to use for the image
    required: false
    default: latest
  kubeconfig:
    description: The kubeconfig to use for acorn
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: acorn-io/actions-setup@v2
      if: ${{ inputs.kubeconfig }}
      with:
        kubeconfig: ${{ inputs.kubeconfig }}
        acorn-init: falses
    - uses: acorn-io/actions-setup@v2
      if: ${{ !inputs.kubeconfig }}
    - uses: acorn-io/actions-login@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build and Push
      shell: bash
      run: |
        acorn build --tag ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }} .
        acorn push ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.tag }}